### ISSUE TITLE
run0 invoked at command line_cannot open display (resolved)

### ISSUE THREAD

**Issue by zeekisthename** [dbergloev/runas#1]
Updated and noticed systemd 256 installed.

Tried run0 and specified file manager and other programs but got:

unable to open display

xhost + did not resolve the issue.

echo $DISPLAY shows :0.0

.bashrc specifies:

export DISPLAY=:0.0

sudo works fine with file manager and other programs opening in X.

Is there a parameter that needs to be specified for .bashrc or .profile in order for run0 to connect to X?

**Comment by dbergloev** [comment]
I only have 256 installed on a headless server, so can't really test this. But running my own script on version 255 works just fine with nautilus on Gnome. May be an X issue? Have not used X for several years, but I would not be surprised if Systemd plays better with Wayland. 

Remember. `sudo` will run things as a child process to your shell wheres systemd will run things as a child to it's own stack. It may not be able to talk to X from there. 

Also, don't use `run0`. It was kind of the point of this repo to begin with :'D

**Comment by zeekisthename** [comment]
run0 --setenv=DISPLAY=$DISPLAY /path/to/target
